# Generated by Django 4.0.4 on 2022-11-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='tittle',
        ),
        migrations.AlterField(
            model_name='task',
            name='content',
            field=models.TextField(blank=True, max_length=128),
        ),
    ]
