# Generated by Django 4.0.4 on 2022-11-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_remove_task_tittle_alter_task_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.BooleanField(choices=[('True', 'Done'), ('False', 'Not done')]),
        ),
    ]
