# Generated by Django 4.0.4 on 2022-11-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.BooleanField(choices=[('True', 'Done'), ('False', 'Not done')], default=False),
        ),
    ]
